In [130]:
import pandas as pd
import warnings
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from matplotlib import rc, rcParams

warnings.filterwarnings('ignore')
rc('font', family='AppleGothic')
rcParams['axes.unicode_minus']= False

###  train_new 파일 
* 지역_lb , 공급유형_lb 원핫인코딩이 되어 있음
* 임대보증금, 임대료 결측치제거한 데이터 프레임
* EDA에 사용
* notnull_df

In [131]:

train = pd.read_csv("../2nd_team/data/train_new.csv")
test = pd.read_csv("../2nd_team/data/test_new.csv")
sub = pd.read_csv('../2nd_team/data/sample_submission.csv')
age = pd.read_csv("../2nd_team/data/age_gender_info.csv")

train.shape, test.shape, sub.shape, age.shape

((3184, 61), (776, 61), (150, 2), (16, 23))

In [132]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3184 entries, 0 to 3183
Data columns (total 61 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   단지코드       3184 non-null   object 
 1   총세대수       3184 non-null   int64  
 2   임대건물구분     3184 non-null   object 
 3   지역         3184 non-null   object 
 4   공급유형       3184 non-null   object 
 5   전용면적       3184 non-null   float64
 6   전용면적별세대수   3184 non-null   int64  
 7   공가수        3184 non-null   float64
 8   자격유형       3184 non-null   object 
 9   임대보증금      3184 non-null   float64
 10  임대료        3184 non-null   float64
 11  지하철        3091 non-null   float64
 12  버스정류장      3184 non-null   float64
 13  단지내주차면수    3184 non-null   float64
 14  임대건물구분_lb  3184 non-null   int64  
 15  상가         3184 non-null   float64
 16  아파트        3184 non-null   float64
 17  지역_lb      3184 non-null   int64  
 18  강원도        3184 non-null   float64
 19  경기도        3184 non-null   float64
 20  경상남도    

In [133]:
train.columns

Index(['단지코드', '총세대수', '임대건물구분', '지역', '공급유형', '전용면적', '전용면적별세대수', '공가수',
       '자격유형', '임대보증금', '임대료', '지하철', '버스정류장', '단지내주차면수', '임대건물구분_lb', '상가',
       '아파트', '지역_lb', '강원도', '경기도', '경상남도', '경상북도', '광주광역시', '대구광역시', '대전광역시',
       '부산광역시', '서울특별시', '세종특별자치시', '울산광역시', '전라남도', '전라북도', '제주특별자치도', '충청남도',
       '충청북도', '공급유형_lb', '공공분양', '공공임대(10년)', '공공임대(50년)', '공공임대(5년)',
       '공공임대(분납)', '국민임대', '영구임대', '임대상가', '장기전세', '행복주택', '자격유형_lb', 'A', 'B',
       'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O'],
      dtype='object')

### 원핫인코딩 확인

In [134]:
train.loc[:, "공공임대(50년)":"행복주택"]

공공임대(50년)  공공임대(5년)  공공임대(분납)  국민임대  영구임대  임대상가  장기전세  행복주택
0           0.0       0.0       0.0   1.0   0.0   0.0   0.0   0.0
1           0.0       0.0       0.0   1.0   0.0   0.0   0.0   0.0
2           0.0       0.0       0.0   1.0   0.0   0.0   0.0   0.0
3           0.0       0.0       0.0   1.0   0.0   0.0   0.0   0.0
4           0.0       0.0       0.0   1.0   0.0   0.0   0.0   0.0
...         ...       ...       ...   ...   ...   ...   ...   ...
3179        0.0       0.0       0.0   0.0   1.0   0.0   0.0   0.0
3180        0.0       0.0       0.0   1.0   0.0   0.0   0.0   0.0
3181        0.0       0.0       0.0   1.0   0.0   0.0   0.0   0.0
3182        0.0       0.0       0.0   1.0   0.0   0.0   0.0   0.0
3183        0.0       0.0       0.0   1.0   0.0   0.0   0.0   0.0

[3184 rows x 8 columns]

In [135]:
train.loc[:, "강원도":"충청북도"]

강원도  경기도  경상남도  경상북도  광주광역시  대구광역시  대전광역시  부산광역시  서울특별시  세종특별자치시  울산광역시  \
0     0.0  0.0   0.0   1.0    0.0    0.0    0.0    0.0    0.0      0.0    0.0   
1     0.0  0.0   0.0   1.0    0.0    0.0    0.0    0.0    0.0      0.0    0.0   
2     0.0  0.0   0.0   1.0    0.0    0.0    0.0    0.0    0.0      0.0    0.0   
3     0.0  0.0   0.0   1.0    0.0    0.0    0.0    0.0    0.0      0.0    0.0   
4     0.0  0.0   0.0   1.0    0.0    0.0    0.0    0.0    0.0      0.0    0.0   
...   ...  ...   ...   ...    ...    ...    ...    ...    ...      ...    ...   
3179  0.0  0.0   1.0   0.0    0.0    0.0    0.0    0.0    0.0      0.0    0.0   
3180  0.0  0.0   0.0   0.0    0.0    0.0    0.0    0.0    0.0      0.0    0.0   
3181  0.0  0.0   0.0   0.0    0.0    0.0    0.0    0.0    0.0      0.0    0.0   
3182  0.0  0.0   0.0   0.0    0.0    0.0    0.0    0.0    0.0      0.0    0.0   
3183  0.0  0.0   0.0   0.0    0.0    0.0    0.0    0.0    0.0      0.0    0.0   

      전라남도  전라북도  제주특별자치도  충청남도  충청북도  
0      0.0   0.0      0.0   0.0   0.0  
1      0.0   0.0      0.0   0.0   0.0  
2      0.0   0.0      0.0   0.0   0.0  
3      0.0   0.0      0.0   0.0   0.0  
4      0.0   0.0      0.0   0.0   0.0  
...    ...   ...      ...   ...   ...  
3179   0.0   0.0      0.0   0.0   0.0  
3180   0.0   1.0      0.0   0.0   0.0  
3181   0.0   1.0      0.0   0.0   0.0  
3182   0.0   1.0      0.0   0.0   0.0  
3183   0.0   1.0      0.0   0.0   0.0  

[3184 rows x 16 columns]

In [136]:
from sklearn.ensemble import RandomForestRegressor
import numpy as np
from sklearn.model_selection import train_test_split

* modle1) '지역_lb', '총세대수', '전용면적','버스정류장','단지내주차면수','공급유형_lb'

In [137]:
# 다수선형회귀
sel = ['지역_lb', '총세대수', '전용면적','버스정류장','단지내주차면수',
      '공급유형_lb']
X = train[sel] #입력
y = train['임대보증금'] #출력

# 일반적으로 X(대문자)는 FEATURE가 1개이상, y는 feature가 1개  

In [138]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,
                                                   random_state=0)

In [139]:
model = RandomForestRegressor(n_estimators=5, random_state=0, n_jobs=-1) # 5개의 트리
model.fit(X_train, y_train)

pred = model.predict(X_test) #X_test 값을 가지고 y_test를 예측해봐 
pred

array([2.51944000e+07, 3.23982000e+07, 9.68000000e+06, 2.30962000e+07,
       5.78700000e+06, 4.62860000e+07, 9.75410000e+07, 3.67348000e+07,
       2.44354000e+07, 2.54808000e+07, 4.12530000e+07, 2.61792000e+07,
       1.44180000e+07, 3.00312000e+07, 3.90000000e+07, 3.00436000e+07,
       4.04486000e+07, 1.41916000e+07, 1.13782000e+07, 2.14634000e+07,
       2.29416000e+07, 1.73950000e+07, 2.12300000e+07, 2.51148000e+07,
       6.80400000e+06, 6.41762000e+07, 1.50516000e+07, 8.76680000e+06,
       1.65382000e+07, 3.34070000e+07, 1.53144000e+07, 4.73286000e+07,
       2.51148000e+07, 1.44180000e+07, 4.82942000e+07, 7.96302000e+07,
       2.09392000e+07, 4.30000000e+07, 2.87970000e+07, 2.05798000e+07,
       2.93424000e+07, 2.60868000e+07, 2.92188000e+07, 4.75354000e+07,
       1.93488000e+07, 3.40820000e+07, 1.04790000e+07, 3.09540000e+07,
       1.78796000e+07, 1.68520000e+07, 3.43568000e+07, 2.58660000e+07,
       1.62460000e+07, 1.48762000e+07, 2.05026000e+07, 2.92340000e+07,
      

In [140]:
print( model.score(X_train, y_train))
print( model.score(X_test, y_test))


0.9521756483570893
0.7185607299768326


In [141]:
# for model in model.estimators_:

# print("학습용 세트 정확도 : {:.3f}".format(model.score(X_train, y_train)))
# print("테스트 세트 정확도 : {:.3f}".format(model.score(X_test, y_test)))
# print() 

* MSE- mean squared error - 평균 제곱 오차   
잔차(오차)의 제곱에 대한 평균을 취한 값  

* MAE - mean absolute error -   평균절대오차 
AE - absolute error - 절대오차  
실제 값과 측정(예측) 값과의 차이   

In [142]:
# mae
mae = np.mean( np.abs(y_test - pred)  )
print(mae)
# mse
mse_val = np.mean( (y_test - pred)**2  )
print(mse_val)


4200766.153616259
93572359485885.66


* modle2) '지역_lb', '총세대수', '전용면적','버스정류장','단지내주차면수','공급유형_lb'

In [143]:
# 다수선형회귀
sel = ['지역_lb', '총세대수', '전용면적','버스정류장','단지내주차면수',
      '공급유형_lb'] #공급유형은 원핫인코딩 한걸로 바꿀것임 
X = train[sel]
y = train['임대료']

In [144]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,
                                                   random_state=0)

In [145]:
model_rent = RandomForestRegressor(n_estimators=5, random_state=0, n_jobs=-1) # 5개의 트리
model_rent.fit(X_train, y_train)

pred = model_rent.predict(X_test) 
pred

array([ 175420.        ,  198620.        ,   81654.        ,
        142558.        ,   79980.        ,  137146.66666667,
         50800.        ,  528000.        ,  172512.        ,
        134416.        ,  499528.        ,  147550.        ,
        100920.        ,  160912.        ,  490000.        ,
        188346.        ,  287164.        ,   97282.        ,
        180460.        ,  165704.        ,  171456.        ,
        201730.        ,  104856.        ,  205918.        ,
         94990.        ,   54552.        ,  137112.        ,
        113038.        ,  114880.        ,  136080.        ,
        112296.        ,  389824.        ,  205918.        ,
        100920.        ,  346772.        ,  541642.        ,
        154648.        ,  470000.        ,  236816.        ,
        176102.        ,  170890.        ,  203866.        ,
        199142.        ,  300584.        ,   96344.        ,
        232200.        ,  117784.        ,  160346.        ,
        148028.        ,

In [146]:
# mae
mae = np.mean( np.abs(y_test - pred)  )
print(mae)
# mse
mse_val = np.mean( (y_test - pred)**2  )
print(mse_val)


22138.554443116158
1403957202.1419296


* modle3) '지역_lb', '총세대수', '전용면적','버스정류장','단지내주차면수','공급유형_lb'

In [147]:
# 다수선형회귀
sel = ['강원도', '경기도', '경상남도', '경상북도', '광주광역시', '대구광역시', '대전광역시',
       '부산광역시', '서울특별시', '세종특별자치시', '울산광역시', '전라남도', '전라북도', '제주특별자치도', '충청남도',
       '충청북도', '총세대수', '전용면적','버스정류장','단지내주차면수',
      '공급유형_lb'] #공급유형은 원핫인코딩 한걸로 바꿀것임 
X = train[sel]
y = train['임대보증금']

In [148]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,
                                                   random_state=0)

In [149]:
model_deposit = RandomForestRegressor(n_estimators=5, random_state=0, n_jobs=-1) # 5개의 트리
model_deposit.fit(X_train, y_train)

pred = model_deposit.predict(X_test) 
pred

array([2.30238000e+07, 3.54298000e+07, 9.79280000e+06, 2.30408000e+07,
       5.78700000e+06, 4.55448000e+07, 9.75410000e+07, 3.48748000e+07,
       1.71680000e+07, 2.36578000e+07, 4.12530000e+07, 2.69136000e+07,
       1.44180000e+07, 3.78432000e+07, 3.90000000e+07, 2.94456000e+07,
       4.21214000e+07, 1.30704000e+07, 1.28742000e+07, 1.96620000e+07,
       2.25384000e+07, 1.73950000e+07, 1.94162000e+07, 2.44536000e+07,
       7.21520000e+06, 6.69918000e+07, 1.62706000e+07, 7.75940000e+06,
       1.70916000e+07, 3.05946000e+07, 1.50014000e+07, 4.61656000e+07,
       2.44536000e+07, 1.44180000e+07, 4.94866000e+07, 8.26776000e+07,
       2.36622000e+07, 4.30000000e+07, 3.24430000e+07, 3.45588000e+07,
       2.29812000e+07, 2.75652000e+07, 2.25018000e+07, 4.60248000e+07,
       1.93488000e+07, 3.40820000e+07, 8.40200000e+06, 2.99880000e+07,
       1.78796000e+07, 1.68520000e+07, 3.33284000e+07, 4.69216000e+07,
       1.53540000e+07, 1.73966000e+07, 2.07070000e+07, 2.51516000e+07,
      

In [150]:
# mae
mae = np.mean( np.abs(y_test - pred)  )
print(mae)
# mse
mse_val = np.mean( (y_test - pred)**2  )
print(mse_val)


3697216.8509663283
77794858834076.1


* modle4) '지역_lb', '총세대수', '전용면적','버스정류장','단지내주차면수','공급유형_lb'

In [151]:
# 다수선형회귀
sel = ['강원도', '경기도', '경상남도', '경상북도', '광주광역시', '대구광역시', '대전광역시',
       '부산광역시', '서울특별시', '세종특별자치시', '울산광역시', '전라남도', '전라북도', '제주특별자치도', '충청남도',
       '충청북도', '총세대수', '전용면적','버스정류장','단지내주차면수',
      '공급유형_lb']
X = train[sel]
y = train['임대료']

In [152]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,
                                                   random_state=0)

In [153]:
model_rent2 = RandomForestRegressor(n_estimators=5, random_state=0, n_jobs=-1) # 5개의 트리
model_rent2.fit(X_train, y_train)

pred = model_rent2.predict(X_test) 
pred

array([ 211060.        ,  179064.        ,   82900.        ,
        135248.        ,   79980.        ,  139278.        ,
         50800.        ,  546000.        ,  169850.        ,
        142012.        ,  510510.        ,  167300.        ,
        100920.        ,  156936.        ,  507000.        ,
        217048.        ,  284650.        ,  116538.        ,
        161596.        ,  131596.        ,  166694.        ,
        201730.        ,  152892.        ,  205918.        ,
         94990.        ,   74224.        ,  136676.        ,
        105638.        ,  101918.        ,  136080.        ,
        118564.        ,  388790.        ,  205918.        ,
        100920.        ,  349402.        ,  500078.        ,
        164354.        ,  470000.        ,  246466.        ,
        190274.        ,  166374.        ,  239984.        ,
        201804.        ,  300584.        ,  113314.        ,
        232200.        ,  106630.        ,  189558.        ,
        145398.        ,

In [154]:
# mae
mae = np.mean( np.abs(y_test - pred)  )
print(mae)
# mse
mse_val = np.mean( (y_test - pred)**2  )
print(mse_val)


22111.240984259814
1355442393.7429292


## 여기까지 

## 아직 안해봄

* modle5) '지역_lb', '총세대수', '전용면적','버스정류장','단지내주차면수','공급유형_lb'

In [ ]:
# 지역_lb, 공급유형_lb, 자격유형_lb → 원핫인코딩 피처로
sel = ['총세대수', '버스정류장', '단지내주차면수', '전용면적', 
       '강원도', '경기도', '경상남도', '경상북도', '광주광역시', '대구광역시', '대전광역시', '부산광역시', 
       '서울특별시', '세종특별자치시', '울산광역시', '전라남도', '전라북도', '제주특별자치도', '충청남도', '충청북도',
       '공공분양', '공공임대(10년)', '공공임대(50년)', '공공임대(5년)',
       '공공임대(분납)', '국민임대', '영구임대', '임대상가', '장기전세', '행복주택']
X = train[sel]
y = train[['임대보증금']]

# 피처스케일링
scaler = MinMaxScaler() # StandardScaler  #우리 생각에 원핫인코딩이 많은 변수는 MinMaxScaler로 하는 게 나을 듯 
X_nor = scaler.fit_transform(X)

# one-hot-encoding
lr = LinearRegression()
knn = KNeighborsRegressor()
rf = RandomForestRegressor()
dt = DecisionTreeRegressor()

# 회귀는 교차검증
lr_scores = cross_val_score(lr, X_nor, y,scoring='neg_mean_absolute_error', cv=5) 
knn_scores = cross_val_score(knn, X_nor, y,scoring='neg_mean_absolute_error', cv=5)
rf_scores = cross_val_score(rf, X_nor, y,scoring='neg_mean_absolute_error', cv=5)
dt_scores = cross_val_score(dt, X_nor, y,scoring='neg_mean_absolute_error', cv=5)

lr_score = np.abs(lr_scores.mean())
knn_score = np.abs(knn_scores.mean())
rf_score = np.abs(rf_scores.mean())
dt_score = np.abs(dt_scores.mean())

print("LinearRegression : ", lr_score)
print("KNeighborsRegressor : ", knn_score)
print("RandomForestRegressor : ", rf_score)
print("DecisionTreeRegressor : ", dt_score)

score_std = [lr_score, knn_score, rf_score, dt_score ]
print(score_std)