### 학습 내용
* RNN에 대해 실습을 통해 알아본다.
* 데이터 셋 : IMDB 영화 리뷰 분류 문제 적용

### 넘파이로 구현한 간단한 RNN

In [1]:
import keras
keras.__version__

'2.6.0'

### 케라스의 순환 층

In [1]:
from keras.layers import SimpleRNN

* SimpleRNN이 한 가지 다른 점은 넘파이 예제처럼 하나의 시퀀스가 아니다.
* 다른 케라스 층과 마찬가지로 시퀀스 배치를 처리
* (timesteps, input_features) 크기 아니다.
* (batch_size, timesteps, input_features) 크기의 입력

In [2]:
timesteps = 100        # 입력 시퀀스에 있는 타입스텝의 수
input_features = 32    # 입력 특성의 차원
output_features = 64   # 출력 특성의 차원

In [4]:
import numpy as np

In [5]:
inputs = np.random.random( (timesteps, input_features)  )
print( inputs.shape )
inputs

(100, 32)


array([[0.14564195, 0.01347344, 0.568832  , ..., 0.52803145, 0.17020982,
        0.3300868 ],
       [0.43520124, 0.59824773, 0.4630459 , ..., 0.55227773, 0.50231612,
        0.38172053],
       [0.36108884, 0.10543013, 0.13170319, ..., 0.49743097, 0.97969088,
        0.96806106],
       ...,
       [0.50866216, 0.14113699, 0.22140127, ..., 0.44714016, 0.8253586 ,
        0.95042412],
       [0.93638558, 0.23601532, 0.16300908, ..., 0.59425491, 0.9026771 ,
        0.69019751],
       [0.65760529, 0.5700206 , 0.68500205, ..., 0.36803799, 0.97741806,
        0.56865521]])

In [6]:
### 초기상태 : 모두 0인 벡터
state_t = np.zeros( (output_features, )) 
print( state_t.shape )
state_t

(64,)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 랜덤한 가중치 행렬

In [11]:
W = np.random.random( (output_features, input_features )) 
U = np.random.random( (output_features, output_features )) 
b = np.random.random( (output_features,  )) 

print(W.shape, U.shape, b.shape)
print(W[0], end='\n\n')
print(U[0], end='\n\n')
print(b[0], end='\n\n')

(64, 32) (64, 64) (64,)
[0.57406839 0.33867977 0.35966179 0.34169977 0.62194013 0.16013766
 0.50113999 0.766811   0.74752315 0.05828997 0.46524108 0.02568946
 0.1632343  0.3513912  0.29335535 0.48573112 0.80996508 0.45292686
 0.61198571 0.60000792 0.51710333 0.99792001 0.47040717 0.51206758
 0.00203562 0.87323174 0.52214518 0.23145849 0.29120086 0.1873022
 0.25643091 0.84189117]

[0.08887078 0.92031651 0.31107234 0.7548734  0.27448716 0.30019644
 0.44267089 0.88379495 0.52419424 0.29316332 0.0700526  0.80679998
 0.17690956 0.58630971 0.74666852 0.25169845 0.43930415 0.54619759
 0.4321799  0.53570745 0.64763579 0.74586032 0.97042613 0.30525761
 0.92030704 0.4863708  0.45794261 0.16268801 0.75665165 0.50682196
 0.30766894 0.98990841 0.91568179 0.66805054 0.48740356 0.86778431
 0.64884826 0.88844007 0.86400816 0.34490263 0.32341795 0.16887914
 0.27697078 0.72346966 0.26861345 0.58374562 0.24021217 0.5032445
 0.79584489 0.71531647 0.83751357 0.02991596 0.02556008 0.54752228
 0.1750075  0.9

In [12]:
W.shape, input_t.shape, U.shape, inputs.shape

NameError: ignored

### 연속된 결과

In [13]:
# inputs = np.random.random( (timesteps, input_features)  )  100, 32
suc_outputs = []
for input_t in inputs:
    print(input_t.shape, input_t)
    
    output_t = np.tanh(np.dot(W, input_t) + np.dot(U, state_t) + b)
    suc_outputs.append(output_t)
    state_t = output_t
    
final_output_sequence = np.stack(suc_outputs, axis=0)

(32,) [0.14564195 0.01347344 0.568832   0.51870213 0.46772448 0.53039214
 0.07964718 0.98834278 0.53349843 0.36848687 0.56316961 0.36674905
 0.08049307 0.17384234 0.78017669 0.79520459 0.03033273 0.89066686
 0.86627155 0.65098175 0.94787996 0.58443314 0.10193924 0.26904671
 0.23891631 0.84649461 0.35625269 0.58556074 0.23728408 0.52803145
 0.17020982 0.3300868 ]
(32,) [0.43520124 0.59824773 0.4630459  0.7607226  0.47522386 0.39183921
 0.2383164  0.41233044 0.89328    0.65772647 0.81659566 0.43652665
 0.40859405 0.10175389 0.21199646 0.4234093  0.24712488 0.96104646
 0.24202751 0.82086005 0.30872174 0.50996693 0.34235618 0.33200902
 0.29005603 0.63359219 0.89666593 0.55795772 0.65997196 0.55227773
 0.50231612 0.38172053]
(32,) [0.36108884 0.10543013 0.13170319 0.5923563  0.55015217 0.89701059
 0.58570191 0.956804   0.43980465 0.50792492 0.77495147 0.05420997
 0.87517925 0.15721536 0.40051959 0.96137111 0.11183148 0.62733897
 0.4798207  0.90272848 0.44730867 0.20115159 0.88466302 0.56900

In [14]:
final_output_sequence.shape

(100, 64)

In [15]:
final_output_sequence[0][0:32]

array([0.9999994 , 0.99999959, 0.99999447, 0.99999877, 0.99999942,
       0.99999977, 0.99999952, 0.99999951, 0.99999934, 0.99999931,
       0.99999983, 0.99999917, 0.99999919, 0.99999788, 0.99999947,
       0.99999888, 0.99996192, 0.99998353, 0.9999995 , 0.99999891,
       0.99999989, 0.99999855, 0.99999983, 0.99999896, 0.99999985,
       0.99999519, 0.9999922 , 0.99999992, 0.99999953, 0.99999641,
       0.99999818, 0.9999962 ])

### 02 케라스를 활용한 RNN 구현
  
* 입력 ( batch_size, timesteps, input_features)
- batch_size : 배치 사이즈
- timesteps : 시간 수준
- input_features : 입력 차원수

### SimpleRNN의 두가지 모드
  
* 1) 각 타임스텝의 출력을 모은 전체 시퀀스를 반환 (batch_size, timesteps, output_feature) 3D텐서
* (2) 입력 시퀀스에 대한 마지막 출력만 반환(batch_size, output_features) 2D텐서
  
* return_sequences의 매개변수로 선택이 가능.

* 2) 입력 시퀀스에 대한 마지막 출력만 반환
* (batch_size, output_features) 2D텐서

In [17]:
from keras.models import Sequential
from keras.layers import Embedding, SimpleRNN

model = Sequential()
model.add(Embedding(10000, 32))  # 시퀀스 길이 10000(10,000지), 차원 32로    
model.add(SimpleRNN(32, return_sequences=False))  #  return_sequences는 기본값이 False
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, None, 32)          320000    
_________________________________________________________________
simple_rnn (SimpleRNN)       (None, 32)                2080      
Total params: 322,080
Trainable params: 322,080
Non-trainable params: 0
_________________________________________________________________


### IMDB 영화 리뷰 분류 문제 적용


In [18]:
from keras.datasets import imdb   #data set 불러오기
from keras.preprocessing import sequence   # 전처리 모듈 불러오기 

### 다양한 길이가 리뷰가 있을 것이다.
* 리뷰에서 맨 마지막 50개 단어를 얻고, 나머지는 버린다. 또는 길이가 짧다면 0으로 채운다.
* 시퀀스의 길이가 50개로 한다.
* 리스트 형태의 리뷰를 2D 정수 텐서로 변환 : preprocessing.sequence.pad_sequences

In [20]:
# 특성으로 사용할 단어의 수 
max_features = 10000    # 80,000 개 단어 사전 중에 우리는 10,000개 단어 까지만 시용하겠다. 그 외 단어는 ? 로 표시된다. 

 # 사용할 텍스트의 길이(가장 빈번한 max_features 개의 단어만 사용합니다)
maxlen = 500    # 리뷰는 500개 까지만
batch_size = 32   # 32개 문장만 

print('데이터 로딩...')
(input_train, y_train), (input_test, y_test) = imdb.load_data(num_words=max_features)
print(len(input_train), '훈련 시퀀스')
print(len(input_test), '테스트 시퀀스')



데이터 로딩...
25000 훈련 시퀀스
25000 테스트 시퀀스


In [21]:
# 문장에서 maxlen 이후의 있는 단어들을 pad_sequences()함수로 잘라낸다.
# 문장 길이가 maxlen보다 작으면 부족한 부분을 0으로 채웁니다. 
print('시퀀스 패딩 (samples x time)')
input_train = sequence.pad_sequences(input_train, maxlen=maxlen)  # sequence.pad_sequences: 빈자리를 0으로 매꿔준다. 
input_test = sequence.pad_sequences(input_test, maxlen=maxlen)
print('input_train 크기:', input_train.shape)
print('input_test 크기:', input_test.shape)

시퀀스 패딩 (samples x time)
input_train 크기: (25000, 500)
input_test 크기: (25000, 500)


In [22]:
%%time

from keras.layers import Dense

model = Sequential()
model.add(Embedding(max_features, 32))
model.add(SimpleRNN(32))
model.add(Dense(1, activation='sigmoid'))


model.summary()

Epoch 1/10
157/157 [==============================] - 65s 390ms/step - loss: 0.6253 - acc: 0.6356 - val_loss: 0.5581 - val_acc: 0.7094
Epoch 2/10
157/157 [==============================] - 60s 385ms/step - loss: 0.3996 - acc: 0.8345 - val_loss: 0.3607 - val_acc: 0.8506
Epoch 3/10
157/157 [==============================] - 61s 389ms/step - loss: 0.2903 - acc: 0.8843 - val_loss: 0.3330 - val_acc: 0.8650
Epoch 4/10
157/157 [==============================] - 61s 389ms/step - loss: 0.2269 - acc: 0.9119 - val_loss: 0.3274 - val_acc: 0.8748
Epoch 5/10
157/157 [==============================] - 61s 391ms/step - loss: 0.1725 - acc: 0.9360 - val_loss: 0.3473 - val_acc: 0.8712
Epoch 6/10
157/157 [==============================] - 61s 391ms/step - loss: 0.1166 - acc: 0.9595 - val_loss: 0.4073 - val_acc: 0.8478
Epoch 7/10
157/157 [==============================] - 61s 388ms/step - loss: 0.0784 - acc: 0.9750 - val_loss: 0.5929 - val_acc: 0.8412
Epoch 8/10
157/157 [==============================] - 6

In [23]:

model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['acc'])  # sigmoid니까,loss='binary_crossentropy'/ 정확도 

history = model.fit(input_train, y_train,
                    epochs=10,
                    batch_size=128,
                    validation_split=0.2)

Epoch 1/10
157/157 [==============================] - 62s 388ms/step - loss: 0.0180 - acc: 0.9955 - val_loss: 0.6816 - val_acc: 0.8152
Epoch 2/10
157/157 [==============================] - 60s 385ms/step - loss: 0.0145 - acc: 0.9958 - val_loss: 0.7315 - val_acc: 0.8150
Epoch 3/10
157/157 [==============================] - 61s 389ms/step - loss: 0.0080 - acc: 0.9980 - val_loss: 0.7220 - val_acc: 0.8194
Epoch 4/10
157/157 [==============================] - 61s 386ms/step - loss: 0.0078 - acc: 0.9977 - val_loss: 0.7183 - val_acc: 0.8342
Epoch 5/10
157/157 [==============================] - 61s 388ms/step - loss: 0.0059 - acc: 0.9985 - val_loss: 0.7810 - val_acc: 0.8236
Epoch 6/10
157/157 [==============================] - 61s 386ms/step - loss: 0.0046 - acc: 0.9987 - val_loss: 0.9124 - val_acc: 0.7842
Epoch 7/10
157/157 [==============================] - 61s 391ms/step - loss: 0.0043 - acc: 0.9984 - val_loss: 1.0943 - val_acc: 0.7488
Epoch 8/10
157/157 [==============================] - 6