### iris classification
- independent var 4개, subordination var 3

X = tf.keras.layers.Input(shape=[4])   
Y = tf.keras.layers.Dense(3, activation='softmax')(X) 


In [3]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [23]:
# 데이터를 준비합니다.
path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(path)
iris.head()


꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [24]:
iris.columns

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종'], dtype='object')

In [25]:
iris = pd.get_dummies(iris)

In [26]:
iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [27]:
iris.columns

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')

In [28]:

features = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
target = iris[['품종_setosa', '품종_versicolor',
       '품종_virginica']]
print(feature .shape, target.shape)
 

(150, 4) (150, 3)


In [29]:
# 모델을 만듭니다.
X = tf.keras.layers.Input(shape=[4]) # input layer을 만듬 # independent var(feature) colum 1
Y = tf.keras.layers.Dense(3, activation='softmax')(X) # dense layer을 만듬  #subordination var(target) colum 1
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [30]:
model.fit(features, target, epochs=1000, verbose=0)
model.fit(features, target, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1690 - accuracy: 0.9667
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1690 - accuracy: 0.9667
Epoch 3/10
5/5 [==============================] - 0s 4ms/step - loss: 0.1692 - accuracy: 0.9667
Epoch 4/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1690 - accuracy: 0.9667
Epoch 5/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1685 - accuracy: 0.9667
Epoch 6/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1687 - accuracy: 0.9667
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1686 - accuracy: 0.9667
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1683 - accuracy: 0.9667
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1688 - accuracy: 0.9667
Epoch 10/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1680 - accuracy: 0.9667


In [ ]:
# 모델을 학습시킵니다. 
model.fit(feature, target, epochs=1000, verbose=0) # verbose=0 : 1000을 출력하는 동안 화면 출력을 하지 않는다.

In [40]:
# 모델을 이용해서 독립변수가 종속변수에 맞게 답을 잘 예측하는지 확인합니다. 
print(model.predict(features[0:5]))
print(target[0:5])


# '품종_setosa'일 확률, '품종_versicolor'일 확률,'품종_virginica'일 확률

[[9.9882752e-01 1.1722118e-03 2.3491209e-07]
 [9.9487692e-01 5.1213531e-03 1.7477539e-06]
 [9.9784803e-01 2.1512127e-03 7.5660455e-07]
 [9.9496788e-01 5.0291382e-03 2.9336995e-06]
 [9.9912769e-01 8.7209931e-04 1.9190163e-07]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [41]:
print(model.predict(features[-5:]))
print(target[-5:])

[[1.4762412e-06 1.4083400e-01 8.5916460e-01]
 [3.3815973e-06 2.5096273e-01 7.4903387e-01]
 [5.9409158e-06 2.3510410e-01 7.6488996e-01]
 [1.3092750e-06 6.6665463e-02 9.3333328e-01]
 [1.3169063e-05 2.1920025e-01 7.8078651e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1
